# Generated by Django 3.2.9 on 2021-11-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsAuditionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CharField', 'CharField'), ('EmailField', 'EmailField')], max_length=100)),
                ('audition_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.auditionbase')),
            ],
        ),
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditions', to='core.auditionbase')),
            ],
        ),
    ]
