# Generated by Django 3.2.9 on 2021-11-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audition_fieldsauditionbase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audition',
            old_name='type',
            new_name='audition_base',
        ),
    ]
