# Generated by Django 3.2.9 on 2021-11-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_type_audition_audition_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldsauditionbase',
            old_name='type',
            new_name='field_type',
        ),
    ]
