# Generated by Django 3.2.9 on 2021-11-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_type_fieldsauditionbase_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldsauditionbase',
            name='choices',
            field=models.TextField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldsauditionbase',
            name='label',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldsauditionbase',
            name='required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
