# Generated by Django 3.2.9 on 2021-11-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211102_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsauditionbase',
            name='choices',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
