# Generated by Django 3.2.9 on 2021-11-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211108_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditionbase',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, unique=True)),
        ),
    ]
