# Generated by Django 3.2.9 on 2021-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditionbase_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='identifier'),
        ),
    ]
