# Generated by Django 3.2.9 on 2021-11-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_audition_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
